[INFO -- 2018-12-03 13:53:39]
Starting flip_value script
version: 1.1
[INFO -- 2018-12-03 13:53:39]
Initialization strings:
[INFO -- 2018-12-03 13:53:39]
(1) file /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/nn
[INFO -- 2018-12-03 13:53:39]
(2) set args /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/filelist 20 5 5 /home/latansini/carol-fi/carol-fi/codes/nnfulldup/nn-knl-files/out20_5_5
[INFO -- 2018-12-03 13:53:39]
initSignal:0
[INFO -- 2018-12-03 13:53:39]
endSignal:2
[INFO -- 2018-12-03 13:53:39]
faultModel:1
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[EXCEPTION -- 2018-12-03 13:53:39]
gdbException: A syntax error in expression, near `...'.
[EXCEPTION -- 2018-12-03 13:53:39]
pythonException: invalid frame
[INFO -- 2018-12-03 13:53:40]
Backtrace BEGIN:
#0  0x00007ffff78d4c7e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78d26f0 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff76b0064 in start_thread (arg=0x7ffff42f6700) at pthread_create.c:309
#3  0x00007ffff73e562d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

188	
189	    filename = argv[1];
190	    k = atoi(argv[2]);
191	    target_lat = atof(argv[3]);
192	    target_long = atof(argv[4]);
193	    gold_filename = argv[5];
194	
195	    data1 = nn_wrapper(filename, k, target_lat, target_long);
196	    data2 = nn_wrapper(filename, k, target_lat, target_long);
197	

Backtrace END
Memory content before bitflip:0x060x000x000x00
Fault Model: Double bit-flip
base address to flip value: 0x7fffffffe44c
address max offset: 4
Memory content after  bitflip:0x060x000x840x00
frame name: main
symbol name: argc
symbol filename: nn.c
symbol line: 176
value: 8650758
value address: 0x7fffffffe44c
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-12-03 13:53:40]
Fault Injection Successful after 1.0317709446s
[INFO -- 2018-12-03 13:53:40]
event type: exit
[EXCEPTION -- 2018-12-03 13:53:40]
exit code: no exit code available
[EXCEPTION -- 2018-12-03 13:53:40]
pythonException: Thread no longer exists.
