[INFO -- 2018-10-18 17:41:14]
Starting flip_value script
version: 1.1
[INFO -- 2018-10-18 17:41:14]
Initialization strings:
[INFO -- 2018-10-18 17:41:14]
(1) file /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/nn
[INFO -- 2018-10-18 17:41:14]
(2) set args /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/filelist 15 25 25 /home/latansini/Desktop/trabalhoftf/carol-fi/sample-code/knn/nn-knl-files/out15_25_25
[INFO -- 2018-10-18 17:41:14]
initSignal:2
[INFO -- 2018-10-18 17:41:14]
endSignal:3
[INFO -- 2018-10-18 17:41:14]
faultModel:2
[EXCEPTION -- 2018-10-18 17:41:16]
gdbException: A syntax error in expression, near `...'.
[EXCEPTION -- 2018-10-18 17:41:16]
pythonException: invalid frame
[EXCEPTION -- 2018-10-18 17:41:16]
pythonException: invalid frame
[EXCEPTION -- 2018-10-18 17:41:16]
pythonException: invalid frame
[INFO -- 2018-10-18 17:41:16]
Backtrace BEGIN:
#0  0x00007ffff78bddf3 in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#1  0x00007ffff78bb6da in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff768f184 in start_thread (arg=0x7ffff68b8700) at pthread_create.c:312
#3  0x00007ffff73bc03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

40	        fprintf(stderr, "%s <filelist> <num neighbors to find> <target latitude> <target longitude> <out filename>\n",argv[0]);
41	        exit(-1);
42	    }
43	
44	    flist = fopen(argv[1], "r");
45	    if(!flist) {
46	        printf("error opening flist\n");
47	        exit(1);
48	    }
49	

Backtrace END
Memory content before bitflip:0x0f0x000x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd500
address max offset: 4
Memory content after  bitflip:0xc10x9b0x340xe2
frame name: main
symbol name: j
symbol filename: nn.c
symbol line: 31
value: -499868735
value address: 0x7fffffffd500
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-10-18 17:41:16]
Fault Injection Successful after 2.2413530349731445s
[INFO -- 2018-10-18 17:41:16]
event type: exit
[EXCEPTION -- 2018-10-18 17:41:16]
exit code: no exit code available
[EXCEPTION -- 2018-10-18 17:41:16]
pythonException: Thread no longer exists.
